### PR TITLE
Added scroll velocity

### PR DESCRIPTION
**Pull request by efremidze**
#1

### CODE REVIEW

**Comment by BohdanOrlov** [comment]
It looks like you changes work for you, but others might have problems, with it (for example you use 5000, not clear where it comes from). 

On which devices you had issue? I'd like to have a look myself.

**Comment by efremidze** [comment]
I completely agree. Im just saying a little bit of velocity makes a difference. You could use any value instead of the 5000, it helps adjust the magnitude of the velocity. This is just a sample of what you could do.

**Comment by BohdanOrlov** [comment]
I'll try your code to understand the difference. Thank you.

**Comment by BohdanOrlov** [comment]
Apparently, I didn't find time for this, my fault  😇
Let me know if this is relevant for anyone, closing for now.

**Pull request closed without merging**
